classDiagram 
 direction RL

%% https://mermaid.js.org/syntax/classDiagram.html

%% define classes

  class Hotel{
   Name
  }
 class Zimmer{
   Nummer
  }

class Mitarbeiter{
  MitarbeiterNummer
}

class Person{
  Name
  Vorname
  Alter
}
   

%% define relations
Zimmer "*" -- "1" Hotel
Mitarbeiter "1..*" -- "1..*" Hotel 
Mitarbeiter --|> Person: inheritance
Hotel "1" -- "1" Zentrale: hat


   